---
- name: Create Azure VM
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    resource_group_name: azure-demo
    region: eastus
    vnet_cidr: 10.0.0.0/16
    subnet_cidr: 10.0.1.0/24
    vnet_name: demo_vnet
    subnet_name: demo_subnet
    network_sec_group_name: demo_sec_group
    win_vm_name: WIN-ansible
    win_vm_size: Standard_DS1_v2
    win_vm_sku: 2022-Datacenter
    win_public_ip_name: win_demo_ip
    win_nic_name: win_demo_nic
    win_admin_user: azureuser
    win_admin_password: ansible123!

  tasks:
  
    - name: import tasks from ../workflow/01-create_resource_group.yml
      ansible.builtin.import_tasks:
        file: ../workflow/01-create_resource_group.yml

    - name: import tasks from ../workflow/02-create_virtual_network.yml
      ansible.builtin.import_tasks:
        file: ../workflow/02-create_virtual_network.yml

    - name: import tasks from ../workflow/03-add_subnet.yml
      ansible.builtin.import_tasks:
        file: ../workflow/03-add_subnet.yml

    - name: import tasks from ../workflow/04-create_public_ip_address.yml
      ansible.builtin.import_tasks:
        file: ../workflow/04-create_public_ip_address.yml

    
    - name: Dump public IP for VM which will be created
      ansible.builtin.debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"
      when: survey_public_ip == "True"

    - name: Set Stat for Ansible Controller
      ansible.builtin.set_stats:
        data:
          azure_vm_public_ip: "{{ output_ip_address.state.ip_address }}"
        per_host: false
      when: survey_public_ip == "True"

    - name: import tasks from ../workflow/05-create_network_security_group.yml
      ansible.builtin.import_tasks:
        file: ../workflow/05-create_network_security_group.yml

    - name: import tasks from ../workflow/06-create_virtual_network_interface_card
      ansible.builtin.import_tasks:
        file: ../workflow/06-create_virtual_network_interface_card.yml


    - name: import tasks from ../workflow/07-create_rhel_vm.yml
      ansible.builtin.import_tasks:
        file: ../workflow/07-create_rhel_vm.yml

    - name: Setup public keys
      when: rhel_public_key is defined
      ansible.builtin.set_fact:
        rhel_ssh_public_keys:
          - path: "/home/{{ rhel_admin_user }}/.ssh/authorized_keys"
            key_data: "{{ rhel_public_key }}"

